apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "relay-proxy.fullname" . }}
  labels:
    app: {{ template "relay-proxy.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
data:
  goff-proxy.yml: | 
    {{ .Files.Get .Values.relayproxy.configurationFile | nindent 4 }}