name: 🐞 Bug Report
description: Found a bug? We are sorry about that! Let us know! 🐛
title: "(bug) <title>"
labels: [bug, needs-triage]
body:
  - type: textarea
    attributes:
      label: Observed behaviour
      description: |
        What are you trying to do?  
        Describe what you think went wrong during this.
        Please provide as many details as possible, such as the components you are using (is it an OpenFeature provider? Which language? etc ...).
    validations:
      required: true
  - type: textarea
    attributes:
      label: Expected Behavior
      description: A concise description of what you expected to happen.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Steps to reproduce
      description: |
        Describe as much as you can the problem.  
        Please provide us with scenario files, logs or anything you have that can help us to understand.
    validations:
      required: false
  - type: markdown
    attributes:
      value: |
        -----
        _ℹ️If you want to work on this issue, please add a comment with `/assign-me` somewhere in your message and the issue will automatically affect you._
