name: Docs new version release

on:
  push:
    branches:
      - main

jobs:
  Documentation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
      - run: |
          cd docs
          npm install
          GIT_USER=thomaspoignant npm run deploy
