name: "Integration Tests"
on:
  pull_request:
    types: [ opened, synchronize, reopened ]

jobs:
  integration-tests:
    name: Integration Tests
    if: startsWith( github.ref_name, 'dependabot/maven/openfeature/provider_tests')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup go
        uses: actions/setup-go@v3
        with:
          go-version: '^1.18.0'
      - name: Set up Maven
        uses: stCarolas/setup-maven@v4.5
        with:
          maven-version: 3.8.2
      - run: make vendor
      - run: make provider-tests