name: test-sonatype-upload
on:
  push:
    branches:
      - sonatype-upload-test

jobs:
  kotlin-release:
    runs-on: ubuntu-latest
    steps:
#      - name: Cache Gradle and wrapper
#        uses: actions/cache@v3
#        with:
#          path: |
#            ~/.gradle/caches
#            ~/.gradle/wrapper
#          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
#          restore-keys: |
#            ${{ runner.os }}-gradle-

      - uses: actions/checkout@v4

      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v6
        with:
          gpg_private_key: ${{ secrets.GPG_SIGNING_KEY }}
          passphrase: ${{ secrets.GPG_SIGNING_KEY_PASSWORD }}
          fingerprint: 9ACC46AB4C1DD2104D5DFB2AFC87955F83FE4262
      - run: ls ~/.gnupg/
#      - name: Configure GPG Key
#        run: |
#          echo -n "$GPG_SIGNING_KEY" | gpg --import
#          gpg --batch --pinentry-mode=loopback --export-secret-key 83FE4262 > ~/.gnupg/secring.gpg
#        env:
#          GPG_SIGNING_KEY: ${{ secrets.GPG_SIGNING_KEY }}

      - name: Add signing secrets to gradle.properties
        run: |
          mkdir -p ~/.gradle/
          echo "signing.keyId=83FE4262" >> ~/.gradle/gradle.properties
          echo "signing.secretKeyRingFile=/home/runner/.gnupg/private-keys-v1.d" >> ~/.gradle/gradle.properties
          echo "signing.password=$GPG_SIGNING_KEY_PASSWORD" >> ~/.gradle/gradle.properties
        env:
          GPG_SIGNING_KEY_ID: ${{ secrets.GPG_SIGNING_KEY_ID }}
          GPG_SIGNING_KEY_PASSWORD: ${{ secrets.GPG_SIGNING_KEY_PASSWORD }}

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'zulu'

      - name: Grant Permission for Gradlew to Execute
        working-directory: ./openfeature/providers/kotlin-provider
        run: chmod +x gradlew
      
      - name: Publish to Sonatype
        env:
          OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
        working-directory: ./openfeature/providers/kotlin-provider
        run: ./gradlew publishToSonatype --no-daemon --stacktrace

      - name: Clean up signing secrets
        working-directory: ./openfeature/providers/kotlin-provider
        run: rm ~/.gradle/gradle.properties
